global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'drachma-testnet'
    static_configs:
      - targets: ['drachma-node-a:9311', 'drachma-node-b:9311']
  - job_name: 'faucet'
    static_configs:
      - targets: ['faucet:9312']
