---
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'drachma-testnet'
    static_configs:
      - targets:
          - 'drachma-seed-a:9311'
          - 'drachma-seed-b:9311'
          - 'drachma-node-1:9311'
          - 'drachma-node-2:9311'
          - 'drachma-node-3:9311'
